### ISSUE TITLE
lack of font-utils.js in bundle

### ISSUE THREAD

**Issue by culee** [sebholstein/astro-google-fonts-optimizer#4]
Cannot use the library in my project because there is a missing `font-utils.js` file in bundle. [https://unpkg.com/browse/astro-google-fonts-optimizer@0.2.0/](https://unpkg.com/browse/astro-google-fonts-optimizer@0.2.0/)

**Comment by bronze** [comment]
same here
` error   failed to load module for ssr: ./font-utils`

**Comment by sebholstein** [comment]
@culee thanks for reporting it. Version 0.2.1 is now released.
