### ISSUE TITLE
Should this be a dev dependency?

### ISSUE THREAD

**Issue by xylarshayu** [sebholstein/astro-google-fonts-optimizer#8]
Hello, thank you so much for project!

I was curious about whether this should be a dev-dependency or just a dependency.

**Comment by sebholstein** [comment]
Hi @xylarshayu 

I think it depends on your rendering mode. If you use SSR, then I would say that it's part of your normal dependencies (as it's needed at runtime). If you just render your site in a static mode, then dev deps would be enough.
